### PR TITLE
WIP Make plugins not global. Revert last-chunk bytes to correct value

### PR DESCRIPTION
**Pull request by slimus**
Make Plugins variable not global to fix concurrency in test
Revert last-chunk in chunked transfer coding to correct value (https://tools.ietf.org/html/rfc2616#section-3.6.1) fyi @bruce34

### CODE REVIEW

**Comment by arijitAD** [comment]
@slimus Are you running the tests parallelly? Because I don't see any race condition if the test runs sequentially. I might be missing something but what I see is that `InitPlugins()` modifies the `Plugins ` inside `registerPlugin()` which is sequentially called at the starting of the program and after that `Plugins` is always read.

**Comment by slimus** [comment]
@arijitAD Thanks for your comment! This problem occur only in race mode (look at this https://travis-ci.org/github/buger/goreplay/builds/691175752)
I want to discuss it today, because sometimes race in tests, sometimes in code. We should stable our tests and run it for each commit

**Comment by arijitAD** [comment]
So after careful investigation, I figured out the reason for the race condition. 
For example in test `TestInputFileWithGET()`. It calls `createCaptureFile()` which updates the `Plugins` variable and calls `Start()` on another goroutine. Then `ReadFromCaptureFile()` is called which is updating the `Plugins` variable and the `Start()` which is running on another goroutine is reading from it. But then I think this issue will be hit only while running the test and not while running the `gor` executable.

**Comment by slimus** [comment]
@arijitAD yes, you are right. But I think we should fix it, because otherwise we can't run tests with race flag and can't find potential problem in code

**Comment by arijitAD** [comment]
Agree. Let's fix the failing test as of now and then come up with a plan to refactor test and code.

**Pull request merged**
