### PR TITLE
chore : Fixed bug risks 

### PR DESCRIPTION
**Pull request by ankitdobhal**
## Description

Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/goreplay/issues/). This PR fixes a few of them.

## Summary of Fixes

- Added .deepsource.toml to fix bug risks
- Empty string test can be improved
- Nested if can be replaced with else-if

## Type of change

- [✔] Antipattern
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [✔] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by buger** [comment]
Hi! 

The thing is that you updated vendor folder, and I actually planning to remove it. 
It would make more sense to send patches to the actual projects.

But having static analyzer running on each PR makes sense.

**Comment by ankitdobhal** [comment]
> Hi!
> 
> The thing is that you updated vendor folder, and I actually planning to remove it.
> It would make more sense to send patches to the actual projects.
> 
> But having static analyzer running on each PR makes sense.

Thanks @buger but should I make this PR ready for review now or not .

**Comment by ankitdobhal** [comment]
> Hi!
> 
> The thing is that you updated vendor folder, and I actually planning to remove it.
> It would make more sense to send patches to the actual projects.
> 
> But having static analyzer running on each PR makes sense.

Thanks @buger for reponse.
But currently the vendor folder is their inside repository.
So I tried to do some antipatttern and bug fixes in repo.

And running static analyzer like [DeepSource](https://deepsource.io/) will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature.

**Comment by ankitdobhal** [comment]
> Hi!
> 
> The thing is that you updated vendor folder, and I actually planning to remove it.
> It would make more sense to send patches to the actual projects.
> 
> But having static analyzer running on each PR makes sense.

Hi @buger as per your suggestion I have updated the PR .
Now kindly go through it and review the changes.

**Comment by ankitdobhal** [comment]
> Hi!
> 
> The thing is that you updated vendor folder, and I actually planning to remove it.
> It would make more sense to send patches to the actual projects.
> 
> But having static analyzer running on each PR makes sense.

@buger kindly review take a look at the PR again, and if found fit, merge the same :)
Thanks a lot!

**Comment by buger** [comment]
Looks solid now! Thanks!

**Comment by ankitdobhal** [comment]
Thanks @buger !
Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature. 

To activate [DeepSource](https://deepsource.io/) you just need to follow these small steps:

- Install DeepSource on your repository [here](https://deepsource.io/signup).
- create .deepsource.toml configuration which you can use to configure your analysis settings.
> Note: This PR already have .deepsource.toml file so after merging you don't to create this one.
- Activate analysis [here](https://deepsource.io/gh/spl0k/supysonic).

**Pull request merged**
