### PR TITLE
release-tars

### PR DESCRIPTION
**Pull request by DimaGolomozy**
- removed deb/rpm/pkg packages
- archiving with `.tar.gz` and `.zip`
- change archive naming

### CODE REVIEW

**Comment by DimaGolomozy** [comment]
@buger please tell me wdyt :)

**Comment by buger** [comment]
Hi! I actually had a different view, deb/rpm quite handly and used a lot. And I was working on adding a proper deb/rpm channels, so you can use apt-get/yum which points to official gor repo. 

As for naming it totally makes sense! 
If you can roll back deb/rpm stuff but keep naming, will be great!

**Comment by DimaGolomozy** [comment]
@buger added the packages back :)

**Comment by buger** [comment]
Looks good!

**Pull request merged**
