### PR TITLE
Add Apache Kafka input

### PR DESCRIPTION
**Pull request by nrwiersma**

### CODE REVIEW

**Comment by buger** [comment]
Hello! Can you describe your use case a bit?

Thank you.

**Comment by nrwiersma** [comment]
Hi, Sure.

We were looking for a way to be able to attach and detach from the replay stream at will with multiple servers simultaneously, while also recording to file or Elasticsearch. By outputting the events into a Kafka stream, we can have multiple replay clients reading the stream at the same time, while also persisting to disk. The replay clients can be booted up and dropped at will, and as they come up, they will join the Kafka stream and start replaying.

**Comment by buger** [comment]
Well it took a long time :) 

I finally merged it, added tests, and compatibility with kafka input changes: https://github.com/buger/goreplay/pull/415

**Comment by nrwiersma** [comment]
Thanks very much, looking great. Great project btw.

**Pull request merged**
